name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /warnaserror
    - name: Set up test environment
      shell: pwsh
      run: ./DockerSdk.Tests/bin/Release/net5.0/scripts/up.ps1
    - name: Show images
      run: docker image ls
    - name: Show containers
      run: docker container ls --all
    - name: Run the tests
      run: dotnet test --configuration Release --no-build --verbosity normal
